name: AWS Systems Manager Run Command
description: Run commands on EC2 instances through SSM

inputs:
  aws-region:
    description: AWS_REGION
    required: true
  document-name:
    description: Document Name
    default: AWS-RunShellScript
    required: false
  parameters:
    description: Parameters depend on document
    required: true
  targets:
    description: Target Instances
    required: true
  timeout:
    description: Timeout to command
    default: '60'
    required: false

outputs:
  command-id:
    description: CommandId to check the details of the command executed
  output:
    description: Command output
  status:
    description: Status of command

runs:
  using: node20
  main: dist/index.js

branding:
  icon: chevron-up
  color: green
